FROM caddy:2-builder AS builder
ARG DNS_PLUGIN=github.com/caddy-dns/duckdns
RUN xcaddy build --with ${DNS_PLUGIN}

FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY caddy-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
